(library
 (name odoc_odoc)
 (public_name odoc.odoc)
 (libraries
  cmdliner
  compiler-libs.common
  fpath
  odoc_markdown
  odoc_latex
  odoc_loader
  odoc_manpage
  odoc_model
  odoc_xref2
  odoc_occurrences
  unix)
 (instrumentation
  (backend landmarks --auto))
 (instrumentation
  (backend bisect_ppx)))

(documentation
 (package odoc))
