A long chain of aliases should produce an odocl file that's a reasonable
size.

  $ ocamlc -c -bin-annot chain.mli
  $ odoc compile chain.cmti
  Starting type_of pass
  Adding (root Chain).A to env
  Adding (root Chain).{M1__}1 to env
  Adding (root Chain).M1 to env
  Adding (root Chain).M1B to env
  Adding (root Chain).{M2__}2 to env
  Adding (root Chain).M2 to env
  Adding (root Chain).M2B to env
  Adding (root Chain).{M3__}3 to env
  Adding (root Chain).M3 to env
  Adding (root Chain).M3B to env
  Adding (root Chain).{M4__}4 to env
  Adding (root Chain).M4 to env
  Adding (root Chain).M4B to env
  Adding (root Chain).{M5__}5 to env
  Adding (root Chain).M5 to env
  Adding (root Chain).M5B to env
  Adding (root Chain).{M6__}6 to env
  Adding (root Chain).M6 to env
  Adding (root Chain).M6B to env
  Adding (root Chain).{M7__}7 to env
  Adding (root Chain).M7 to env
  Adding (root Chain).M7B to env
  Adding (root Chain).{M8__}8 to env
  Adding (root Chain).M8 to env
  Adding (root Chain).M8B to env
  Adding (root Chain).{M9__}9 to env
  Adding (root Chain).M9 to env
  Adding (root Chain).M9B to env
  Adding (root Chain).{M10__}10 to env
  Adding (root Chain).M10 to env
  Adding (root Chain).M10B to env
  Adding (root Chain).{M11__}11 to env
  Adding (root Chain).M11 to env
  Adding (root Chain).M11B to env
  Adding (root Chain).{M12__}12 to env
  Adding (root Chain).M12 to env
  Adding (root Chain).M12B to env
  Adding (root Chain).{M13__}13 to env
  Adding (root Chain).M13 to env
  Adding (root Chain).M13B to env
  Adding (root Chain).{M14__}14 to env
  Adding (root Chain).M14 to env
  Adding (root Chain).M14B to env
  Adding (root Chain).{M15__}15 to env
  Adding (root Chain).M15 to env
  Adding (root Chain).M15B to env
  Adding (root Chain).{M16__}16 to env
  Adding (root Chain).M16 to env
  Adding (root Chain).M16B to env
  Adding (root Chain).{M17__}17 to env
  Adding (root Chain).M17 to env
  Adding (root Chain).M17B to env
  Adding (root Chain).{M18__}18 to env
  Adding (root Chain).M18 to env
  Adding (root Chain).M18B to env
  Adding (root Chain).{M19__}19 to env
  Adding (root Chain).M19 to env
  Adding (root Chain).M19B to env
  Adding (root Chain).{M20__}20 to env
  Adding (root Chain).M20 to env
  Adding (root Chain).M20B to env
  Adding (root Chain).{M21__}21 to env
  Adding (root Chain).M21 to env
  Adding (root Chain).M21B to env
  Adding (root Chain).{M22__}22 to env
  Adding (root Chain).M22 to env
  Adding (root Chain).M22B to env
  Adding (root Chain).{M23__}23 to env
  Adding (root Chain).M23 to env
  Adding (root Chain).M23B to env
  Adding (root Chain).{M24__}24 to env
  Adding (root Chain).M24 to env
  Adding (root Chain).M24B to env
  Adding (root Chain).{M25__}25 to env
  Adding (root Chain).M25 to env
  Adding (root Chain).M25B to env
  Adding (root Chain).{M26__}26 to env
  Adding (root Chain).M26 to env
  Adding (root Chain).M26B to env
  Adding (root Chain).{M27__}27 to env
  Adding (root Chain).M27 to env
  Adding (root Chain).M27B to env
  Adding (root Chain).{M28__}28 to env
  Adding (root Chain).M28 to env
  Adding (root Chain).M28B to env
  Adding (root Chain).{M29__}29 to env
  Adding (root Chain).M29 to env
  Adding (root Chain).M29B to env
  Adding (root Chain).{M30__}30 to env
  Adding (root Chain).M30 to env
  Adding (root Chain).M30B to env
  Adding (root Chain).{M31__}31 to env
  Adding (root Chain).M31 to env
  Adding (root Chain).M31B to env
  Adding (root Chain).{M32__}32 to env
  Adding (root Chain).M32 to env
  Adding (root Chain).M32B to env
  Adding (root Chain).{M33__}33 to env
  Adding (root Chain).M33 to env
  Adding (root Chain).M33B to env
  Adding (root Chain).{M34__}34 to env
  Adding (root Chain).M34 to env
  Adding (root Chain).M34B to env
  Adding (root Chain).{M35__}35 to env
  Adding (root Chain).M35 to env
  Adding (root Chain).M35B to env
  Adding (root Chain).{M36__}36 to env
  Adding (root Chain).M36 to env
  Adding (root Chain).M36B to env
  Adding (root Chain).{M37__}37 to env
  Adding (root Chain).M37 to env
  Adding (root Chain).M37B to env
  Adding (root Chain).{M38__}38 to env
  Adding (root Chain).M38 to env
  Adding (root Chain).M38B to env
  Adding (root Chain).{M39__}39 to env
  Adding (root Chain).M39 to env
  Adding (root Chain).M39B to env
  Adding (root Chain).{M40__}40 to env
  Adding (root Chain).M40 to env
  Adding (root Chain).M40B to env
  Adding (root Chain).{M41__}41 to env
  Adding (root Chain).M41 to env
  Adding (root Chain).M41B to env
  Adding (root Chain).{M42__}42 to env
  Adding (root Chain).M42 to env
  Adding (root Chain).M42B to env
  Adding (root Chain).{M43__}43 to env
  Adding (root Chain).M43 to env
  Adding (root Chain).M43B to env
  Adding (root Chain).{M44__}44 to env
  Adding (root Chain).M44 to env
  Adding (root Chain).M44B to env
  Adding (root Chain).{M45__}45 to env
  Adding (root Chain).M45 to env
  Adding (root Chain).M45B to env
  Adding (root Chain).{M46__}46 to env
  Adding (root Chain).M46 to env
  Adding (root Chain).M46B to env
  Adding (root Chain).{M47__}47 to env
  Adding (root Chain).M47 to env
  Adding (root Chain).M47B to env
  Adding (root Chain).{M48__}48 to env
  Adding (root Chain).M48 to env
  Adding (root Chain).M48B to env
  Adding (root Chain).{M49__}49 to env
  Adding (root Chain).M49 to env
  Adding (root Chain).M49B to env
  Adding (root Chain).{M50__}50 to env
  Adding (root Chain).M50 to env
  Adding (root Chain).M50B to env
  Adding (root Chain).{M51__}51 to env
  Adding (root Chain).M51 to env
  Adding (root Chain).M51B to env
  Adding (root Chain).{M52__}52 to env
  Adding (root Chain).M52 to env
  Adding (root Chain).M52B to env
  Adding (root Chain).{M53__}53 to env
  Adding (root Chain).M53 to env
  Adding (root Chain).M53B to env
  Adding (root Chain).{M54__}54 to env
  Adding (root Chain).M54 to env
  Adding (root Chain).M54B to env
  Adding (root Chain).{M55__}55 to env
  Adding (root Chain).M55 to env
  Adding (root Chain).M55B to env
  Adding (root Chain).{M56__}56 to env
  Adding (root Chain).M56 to env
  Adding (root Chain).M56B to env
  Adding (root Chain).{M57__}57 to env
  Adding (root Chain).M57 to env
  Adding (root Chain).M57B to env
  Adding (root Chain).{M58__}58 to env
  Adding (root Chain).M58 to env
  Adding (root Chain).M58B to env
  Adding (root Chain).{M59__}59 to env
  Adding (root Chain).M59 to env
  Adding (root Chain).M59B to env
  Adding (root Chain).{M60__}60 to env
  Adding (root Chain).M60 to env
  Adding (root Chain).M60B to env
  Adding (root Chain).{M61__}61 to env
  Adding (root Chain).M61 to env
  Adding (root Chain).M61B to env
  Adding (root Chain).{M62__}62 to env
  Adding (root Chain).M62 to env
  Adding (root Chain).M62B to env
  Adding (root Chain).{M63__}63 to env
  Adding (root Chain).M63 to env
  Adding (root Chain).M63B to env
  Adding (root Chain).{M64__}64 to env
  Adding (root Chain).M64 to env
  Adding (root Chain).M64B to env
  Adding (root Chain).{M65__}65 to env
  Adding (root Chain).M65 to env
  Adding (root Chain).M65B to env
  Adding (root Chain).{M66__}66 to env
  Adding (root Chain).M66 to env
  Adding (root Chain).M66B to env
  Adding (root Chain).{M67__}67 to env
  Adding (root Chain).M67 to env
  Adding (root Chain).M67B to env
  Adding (root Chain).{M68__}68 to env
  Adding (root Chain).M68 to env
  Adding (root Chain).M68B to env
  Adding (root Chain).{M69__}69 to env
  Adding (root Chain).M69 to env
  Adding (root Chain).M69B to env
  Adding (root Chain).{M70__}70 to env
  Adding (root Chain).M70 to env
  Adding (root Chain).M70B to env
  Adding (root Chain).{M71__}71 to env
  Adding (root Chain).M71 to env
  Adding (root Chain).M71B to env
  Adding (root Chain).{M72__}72 to env
  Adding (root Chain).M72 to env
  Adding (root Chain).M72B to env
  Adding (root Chain).{M73__}73 to env
  Adding (root Chain).M73 to env
  Adding (root Chain).M73B to env
  Adding (root Chain).{M74__}74 to env
  Adding (root Chain).M74 to env
  Adding (root Chain).M74B to env
  Adding (root Chain).{M75__}75 to env
  Adding (root Chain).M75 to env
  Adding (root Chain).M75B to env
  Adding (root Chain).{M76__}76 to env
  Adding (root Chain).M76 to env
  Adding (root Chain).M76B to env
  Adding (root Chain).{M77__}77 to env
  Adding (root Chain).M77 to env
  Adding (root Chain).M77B to env
  Adding (root Chain).{M78__}78 to env
  Adding (root Chain).M78 to env
  Adding (root Chain).M78B to env
  Adding (root Chain).{M79__}79 to env
  Adding (root Chain).M79 to env
  Adding (root Chain).M79B to env
  Adding (root Chain).{M80__}80 to env
  Adding (root Chain).M80 to env
  Adding (root Chain).M80B to env
  Adding (root Chain).{M81__}81 to env
  Adding (root Chain).M81 to env
  Adding (root Chain).M81B to env
  Adding (root Chain).{M82__}82 to env
  Adding (root Chain).M82 to env
  Adding (root Chain).M82B to env
  Adding (root Chain).{M83__}83 to env
  Adding (root Chain).M83 to env
  Adding (root Chain).M83B to env
  Adding (root Chain).{M84__}84 to env
  Adding (root Chain).M84 to env
  Adding (root Chain).M84B to env
  Adding (root Chain).{M85__}85 to env
  Adding (root Chain).M85 to env
  Adding (root Chain).M85B to env
  Adding (root Chain).{M86__}86 to env
  Adding (root Chain).M86 to env
  Adding (root Chain).M86B to env
  Adding (root Chain).{M87__}87 to env
  Adding (root Chain).M87 to env
  Adding (root Chain).M87B to env
  Adding (root Chain).{M88__}88 to env
  Adding (root Chain).M88 to env
  Adding (root Chain).M88B to env
  Adding (root Chain).{M89__}89 to env
  Adding (root Chain).M89 to env
  Adding (root Chain).M89B to env
  Adding (root Chain).{M90__}90 to env
  Adding (root Chain).M90 to env
  Adding (root Chain).M90B to env
  Adding (root Chain).{M91__}91 to env
  Adding (root Chain).M91 to env
  Adding (root Chain).M91B to env
  Adding (root Chain).{M92__}92 to env
  Adding (root Chain).M92 to env
  Adding (root Chain).M92B to env
  Adding (root Chain).{M93__}93 to env
  Adding (root Chain).M93 to env
  Adding (root Chain).M93B to env
  Adding (root Chain).{M94__}94 to env
  Adding (root Chain).M94 to env
  Adding (root Chain).M94B to env
  Adding (root Chain).{M95__}95 to env
  Adding (root Chain).M95 to env
  Adding (root Chain).M95B to env
  Adding (root Chain).{M96__}96 to env
  Adding (root Chain).M96 to env
  Adding (root Chain).M96B to env
  Adding (root Chain).{M97__}97 to env
  Adding (root Chain).M97 to env
  Adding (root Chain).M97B to env
  Adding (root Chain).{M98__}98 to env
  Adding (root Chain).M98 to env
  Adding (root Chain).M98B to env
  Adding (root Chain).{M99__}99 to env
  Adding (root Chain).M99 to env
  Adding (root Chain).M99B to env
  Adding (root Chain).{M100__}100 to env
  Adding (root Chain).M100 to env
  Adding (root Chain).M100B to env
  Adding (root Chain).A.B to env
  Adding (root Chain).A.B.t to env
  Finished type_of pass
  Adding (root Chain).A to env
  Adding (root Chain).{M1__}1 to env
  Adding (root Chain).M1 to env
  Adding (root Chain).M1B to env
  Adding (root Chain).{M2__}2 to env
  Adding (root Chain).M2 to env
  Adding (root Chain).M2B to env
  Adding (root Chain).{M3__}3 to env
  Adding (root Chain).M3 to env
  Adding (root Chain).M3B to env
  Adding (root Chain).{M4__}4 to env
  Adding (root Chain).M4 to env
  Adding (root Chain).M4B to env
  Adding (root Chain).{M5__}5 to env
  Adding (root Chain).M5 to env
  Adding (root Chain).M5B to env
  Adding (root Chain).{M6__}6 to env
  Adding (root Chain).M6 to env
  Adding (root Chain).M6B to env
  Adding (root Chain).{M7__}7 to env
  Adding (root Chain).M7 to env
  Adding (root Chain).M7B to env
  Adding (root Chain).{M8__}8 to env
  Adding (root Chain).M8 to env
  Adding (root Chain).M8B to env
  Adding (root Chain).{M9__}9 to env
  Adding (root Chain).M9 to env
  Adding (root Chain).M9B to env
  Adding (root Chain).{M10__}10 to env
  Adding (root Chain).M10 to env
  Adding (root Chain).M10B to env
  Adding (root Chain).{M11__}11 to env
  Adding (root Chain).M11 to env
  Adding (root Chain).M11B to env
  Adding (root Chain).{M12__}12 to env
  Adding (root Chain).M12 to env
  Adding (root Chain).M12B to env
  Adding (root Chain).{M13__}13 to env
  Adding (root Chain).M13 to env
  Adding (root Chain).M13B to env
  Adding (root Chain).{M14__}14 to env
  Adding (root Chain).M14 to env
  Adding (root Chain).M14B to env
  Adding (root Chain).{M15__}15 to env
  Adding (root Chain).M15 to env
  Adding (root Chain).M15B to env
  Adding (root Chain).{M16__}16 to env
  Adding (root Chain).M16 to env
  Adding (root Chain).M16B to env
  Adding (root Chain).{M17__}17 to env
  Adding (root Chain).M17 to env
  Adding (root Chain).M17B to env
  Adding (root Chain).{M18__}18 to env
  Adding (root Chain).M18 to env
  Adding (root Chain).M18B to env
  Adding (root Chain).{M19__}19 to env
  Adding (root Chain).M19 to env
  Adding (root Chain).M19B to env
  Adding (root Chain).{M20__}20 to env
  Adding (root Chain).M20 to env
  Adding (root Chain).M20B to env
  Adding (root Chain).{M21__}21 to env
  Adding (root Chain).M21 to env
  Adding (root Chain).M21B to env
  Adding (root Chain).{M22__}22 to env
  Adding (root Chain).M22 to env
  Adding (root Chain).M22B to env
  Adding (root Chain).{M23__}23 to env
  Adding (root Chain).M23 to env
  Adding (root Chain).M23B to env
  Adding (root Chain).{M24__}24 to env
  Adding (root Chain).M24 to env
  Adding (root Chain).M24B to env
  Adding (root Chain).{M25__}25 to env
  Adding (root Chain).M25 to env
  Adding (root Chain).M25B to env
  Adding (root Chain).{M26__}26 to env
  Adding (root Chain).M26 to env
  Adding (root Chain).M26B to env
  Adding (root Chain).{M27__}27 to env
  Adding (root Chain).M27 to env
  Adding (root Chain).M27B to env
  Adding (root Chain).{M28__}28 to env
  Adding (root Chain).M28 to env
  Adding (root Chain).M28B to env
  Adding (root Chain).{M29__}29 to env
  Adding (root Chain).M29 to env
  Adding (root Chain).M29B to env
  Adding (root Chain).{M30__}30 to env
  Adding (root Chain).M30 to env
  Adding (root Chain).M30B to env
  Adding (root Chain).{M31__}31 to env
  Adding (root Chain).M31 to env
  Adding (root Chain).M31B to env
  Adding (root Chain).{M32__}32 to env
  Adding (root Chain).M32 to env
  Adding (root Chain).M32B to env
  Adding (root Chain).{M33__}33 to env
  Adding (root Chain).M33 to env
  Adding (root Chain).M33B to env
  Adding (root Chain).{M34__}34 to env
  Adding (root Chain).M34 to env
  Adding (root Chain).M34B to env
  Adding (root Chain).{M35__}35 to env
  Adding (root Chain).M35 to env
  Adding (root Chain).M35B to env
  Adding (root Chain).{M36__}36 to env
  Adding (root Chain).M36 to env
  Adding (root Chain).M36B to env
  Adding (root Chain).{M37__}37 to env
  Adding (root Chain).M37 to env
  Adding (root Chain).M37B to env
  Adding (root Chain).{M38__}38 to env
  Adding (root Chain).M38 to env
  Adding (root Chain).M38B to env
  Adding (root Chain).{M39__}39 to env
  Adding (root Chain).M39 to env
  Adding (root Chain).M39B to env
  Adding (root Chain).{M40__}40 to env
  Adding (root Chain).M40 to env
  Adding (root Chain).M40B to env
  Adding (root Chain).{M41__}41 to env
  Adding (root Chain).M41 to env
  Adding (root Chain).M41B to env
  Adding (root Chain).{M42__}42 to env
  Adding (root Chain).M42 to env
  Adding (root Chain).M42B to env
  Adding (root Chain).{M43__}43 to env
  Adding (root Chain).M43 to env
  Adding (root Chain).M43B to env
  Adding (root Chain).{M44__}44 to env
  Adding (root Chain).M44 to env
  Adding (root Chain).M44B to env
  Adding (root Chain).{M45__}45 to env
  Adding (root Chain).M45 to env
  Adding (root Chain).M45B to env
  Adding (root Chain).{M46__}46 to env
  Adding (root Chain).M46 to env
  Adding (root Chain).M46B to env
  Adding (root Chain).{M47__}47 to env
  Adding (root Chain).M47 to env
  Adding (root Chain).M47B to env
  Adding (root Chain).{M48__}48 to env
  Adding (root Chain).M48 to env
  Adding (root Chain).M48B to env
  Adding (root Chain).{M49__}49 to env
  Adding (root Chain).M49 to env
  Adding (root Chain).M49B to env
  Adding (root Chain).{M50__}50 to env
  Adding (root Chain).M50 to env
  Adding (root Chain).M50B to env
  Adding (root Chain).{M51__}51 to env
  Adding (root Chain).M51 to env
  Adding (root Chain).M51B to env
  Adding (root Chain).{M52__}52 to env
  Adding (root Chain).M52 to env
  Adding (root Chain).M52B to env
  Adding (root Chain).{M53__}53 to env
  Adding (root Chain).M53 to env
  Adding (root Chain).M53B to env
  Adding (root Chain).{M54__}54 to env
  Adding (root Chain).M54 to env
  Adding (root Chain).M54B to env
  Adding (root Chain).{M55__}55 to env
  Adding (root Chain).M55 to env
  Adding (root Chain).M55B to env
  Adding (root Chain).{M56__}56 to env
  Adding (root Chain).M56 to env
  Adding (root Chain).M56B to env
  Adding (root Chain).{M57__}57 to env
  Adding (root Chain).M57 to env
  Adding (root Chain).M57B to env
  Adding (root Chain).{M58__}58 to env
  Adding (root Chain).M58 to env
  Adding (root Chain).M58B to env
  Adding (root Chain).{M59__}59 to env
  Adding (root Chain).M59 to env
  Adding (root Chain).M59B to env
  Adding (root Chain).{M60__}60 to env
  Adding (root Chain).M60 to env
  Adding (root Chain).M60B to env
  Adding (root Chain).{M61__}61 to env
  Adding (root Chain).M61 to env
  Adding (root Chain).M61B to env
  Adding (root Chain).{M62__}62 to env
  Adding (root Chain).M62 to env
  Adding (root Chain).M62B to env
  Adding (root Chain).{M63__}63 to env
  Adding (root Chain).M63 to env
  Adding (root Chain).M63B to env
  Adding (root Chain).{M64__}64 to env
  Adding (root Chain).M64 to env
  Adding (root Chain).M64B to env
  Adding (root Chain).{M65__}65 to env
  Adding (root Chain).M65 to env
  Adding (root Chain).M65B to env
  Adding (root Chain).{M66__}66 to env
  Adding (root Chain).M66 to env
  Adding (root Chain).M66B to env
  Adding (root Chain).{M67__}67 to env
  Adding (root Chain).M67 to env
  Adding (root Chain).M67B to env
  Adding (root Chain).{M68__}68 to env
  Adding (root Chain).M68 to env
  Adding (root Chain).M68B to env
  Adding (root Chain).{M69__}69 to env
  Adding (root Chain).M69 to env
  Adding (root Chain).M69B to env
  Adding (root Chain).{M70__}70 to env
  Adding (root Chain).M70 to env
  Adding (root Chain).M70B to env
  Adding (root Chain).{M71__}71 to env
  Adding (root Chain).M71 to env
  Adding (root Chain).M71B to env
  Adding (root Chain).{M72__}72 to env
  Adding (root Chain).M72 to env
  Adding (root Chain).M72B to env
  Adding (root Chain).{M73__}73 to env
  Adding (root Chain).M73 to env
  Adding (root Chain).M73B to env
  Adding (root Chain).{M74__}74 to env
  Adding (root Chain).M74 to env
  Adding (root Chain).M74B to env
  Adding (root Chain).{M75__}75 to env
  Adding (root Chain).M75 to env
  Adding (root Chain).M75B to env
  Adding (root Chain).{M76__}76 to env
  Adding (root Chain).M76 to env
  Adding (root Chain).M76B to env
  Adding (root Chain).{M77__}77 to env
  Adding (root Chain).M77 to env
  Adding (root Chain).M77B to env
  Adding (root Chain).{M78__}78 to env
  Adding (root Chain).M78 to env
  Adding (root Chain).M78B to env
  Adding (root Chain).{M79__}79 to env
  Adding (root Chain).M79 to env
  Adding (root Chain).M79B to env
  Adding (root Chain).{M80__}80 to env
  Adding (root Chain).M80 to env
  Adding (root Chain).M80B to env
  Adding (root Chain).{M81__}81 to env
  Adding (root Chain).M81 to env
  Adding (root Chain).M81B to env
  Adding (root Chain).{M82__}82 to env
  Adding (root Chain).M82 to env
  Adding (root Chain).M82B to env
  Adding (root Chain).{M83__}83 to env
  Adding (root Chain).M83 to env
  Adding (root Chain).M83B to env
  Adding (root Chain).{M84__}84 to env
  Adding (root Chain).M84 to env
  Adding (root Chain).M84B to env
  Adding (root Chain).{M85__}85 to env
  Adding (root Chain).M85 to env
  Adding (root Chain).M85B to env
  Adding (root Chain).{M86__}86 to env
  Adding (root Chain).M86 to env
  Adding (root Chain).M86B to env
  Adding (root Chain).{M87__}87 to env
  Adding (root Chain).M87 to env
  Adding (root Chain).M87B to env
  Adding (root Chain).{M88__}88 to env
  Adding (root Chain).M88 to env
  Adding (root Chain).M88B to env
  Adding (root Chain).{M89__}89 to env
  Adding (root Chain).M89 to env
  Adding (root Chain).M89B to env
  Adding (root Chain).{M90__}90 to env
  Adding (root Chain).M90 to env
  Adding (root Chain).M90B to env
  Adding (root Chain).{M91__}91 to env
  Adding (root Chain).M91 to env
  Adding (root Chain).M91B to env
  Adding (root Chain).{M92__}92 to env
  Adding (root Chain).M92 to env
  Adding (root Chain).M92B to env
  Adding (root Chain).{M93__}93 to env
  Adding (root Chain).M93 to env
  Adding (root Chain).M93B to env
  Adding (root Chain).{M94__}94 to env
  Adding (root Chain).M94 to env
  Adding (root Chain).M94B to env
  Adding (root Chain).{M95__}95 to env
  Adding (root Chain).M95 to env
  Adding (root Chain).M95B to env
  Adding (root Chain).{M96__}96 to env
  Adding (root Chain).M96 to env
  Adding (root Chain).M96B to env
  Adding (root Chain).{M97__}97 to env
  Adding (root Chain).M97 to env
  Adding (root Chain).M97B to env
  Adding (root Chain).{M98__}98 to env
  Adding (root Chain).M98 to env
  Adding (root Chain).M98B to env
  Adding (root Chain).{M99__}99 to env
  Adding (root Chain).M99 to env
  Adding (root Chain).M99B to env
  Adding (root Chain).{M100__}100 to env
  Adding (root Chain).M100 to env
  Adding (root Chain).M100B to env
  Adding (root Chain).A.B to env
  Adding (root Chain).A.B.t to env
  $ odoc link chain.odoc -I .
  Adding (root Chain).A to env
  Adding (root Chain).{M1__}1 to env
  Adding (root Chain).M1 to env
  Adding (root Chain).M1B to env
  Adding (root Chain).{M2__}2 to env
  Adding (root Chain).M2 to env
  Adding (root Chain).M2B to env
  Adding (root Chain).{M3__}3 to env
  Adding (root Chain).M3 to env
  Adding (root Chain).M3B to env
  Adding (root Chain).{M4__}4 to env
  Adding (root Chain).M4 to env
  Adding (root Chain).M4B to env
  Adding (root Chain).{M5__}5 to env
  Adding (root Chain).M5 to env
  Adding (root Chain).M5B to env
  Adding (root Chain).{M6__}6 to env
  Adding (root Chain).M6 to env
  Adding (root Chain).M6B to env
  Adding (root Chain).{M7__}7 to env
  Adding (root Chain).M7 to env
  Adding (root Chain).M7B to env
  Adding (root Chain).{M8__}8 to env
  Adding (root Chain).M8 to env
  Adding (root Chain).M8B to env
  Adding (root Chain).{M9__}9 to env
  Adding (root Chain).M9 to env
  Adding (root Chain).M9B to env
  Adding (root Chain).{M10__}10 to env
  Adding (root Chain).M10 to env
  Adding (root Chain).M10B to env
  Adding (root Chain).{M11__}11 to env
  Adding (root Chain).M11 to env
  Adding (root Chain).M11B to env
  Adding (root Chain).{M12__}12 to env
  Adding (root Chain).M12 to env
  Adding (root Chain).M12B to env
  Adding (root Chain).{M13__}13 to env
  Adding (root Chain).M13 to env
  Adding (root Chain).M13B to env
  Adding (root Chain).{M14__}14 to env
  Adding (root Chain).M14 to env
  Adding (root Chain).M14B to env
  Adding (root Chain).{M15__}15 to env
  Adding (root Chain).M15 to env
  Adding (root Chain).M15B to env
  Adding (root Chain).{M16__}16 to env
  Adding (root Chain).M16 to env
  Adding (root Chain).M16B to env
  Adding (root Chain).{M17__}17 to env
  Adding (root Chain).M17 to env
  Adding (root Chain).M17B to env
  Adding (root Chain).{M18__}18 to env
  Adding (root Chain).M18 to env
  Adding (root Chain).M18B to env
  Adding (root Chain).{M19__}19 to env
  Adding (root Chain).M19 to env
  Adding (root Chain).M19B to env
  Adding (root Chain).{M20__}20 to env
  Adding (root Chain).M20 to env
  Adding (root Chain).M20B to env
  Adding (root Chain).{M21__}21 to env
  Adding (root Chain).M21 to env
  Adding (root Chain).M21B to env
  Adding (root Chain).{M22__}22 to env
  Adding (root Chain).M22 to env
  Adding (root Chain).M22B to env
  Adding (root Chain).{M23__}23 to env
  Adding (root Chain).M23 to env
  Adding (root Chain).M23B to env
  Adding (root Chain).{M24__}24 to env
  Adding (root Chain).M24 to env
  Adding (root Chain).M24B to env
  Adding (root Chain).{M25__}25 to env
  Adding (root Chain).M25 to env
  Adding (root Chain).M25B to env
  Adding (root Chain).{M26__}26 to env
  Adding (root Chain).M26 to env
  Adding (root Chain).M26B to env
  Adding (root Chain).{M27__}27 to env
  Adding (root Chain).M27 to env
  Adding (root Chain).M27B to env
  Adding (root Chain).{M28__}28 to env
  Adding (root Chain).M28 to env
  Adding (root Chain).M28B to env
  Adding (root Chain).{M29__}29 to env
  Adding (root Chain).M29 to env
  Adding (root Chain).M29B to env
  Adding (root Chain).{M30__}30 to env
  Adding (root Chain).M30 to env
  Adding (root Chain).M30B to env
  Adding (root Chain).{M31__}31 to env
  Adding (root Chain).M31 to env
  Adding (root Chain).M31B to env
  Adding (root Chain).{M32__}32 to env
  Adding (root Chain).M32 to env
  Adding (root Chain).M32B to env
  Adding (root Chain).{M33__}33 to env
  Adding (root Chain).M33 to env
  Adding (root Chain).M33B to env
  Adding (root Chain).{M34__}34 to env
  Adding (root Chain).M34 to env
  Adding (root Chain).M34B to env
  Adding (root Chain).{M35__}35 to env
  Adding (root Chain).M35 to env
  Adding (root Chain).M35B to env
  Adding (root Chain).{M36__}36 to env
  Adding (root Chain).M36 to env
  Adding (root Chain).M36B to env
  Adding (root Chain).{M37__}37 to env
  Adding (root Chain).M37 to env
  Adding (root Chain).M37B to env
  Adding (root Chain).{M38__}38 to env
  Adding (root Chain).M38 to env
  Adding (root Chain).M38B to env
  Adding (root Chain).{M39__}39 to env
  Adding (root Chain).M39 to env
  Adding (root Chain).M39B to env
  Adding (root Chain).{M40__}40 to env
  Adding (root Chain).M40 to env
  Adding (root Chain).M40B to env
  Adding (root Chain).{M41__}41 to env
  Adding (root Chain).M41 to env
  Adding (root Chain).M41B to env
  Adding (root Chain).{M42__}42 to env
  Adding (root Chain).M42 to env
  Adding (root Chain).M42B to env
  Adding (root Chain).{M43__}43 to env
  Adding (root Chain).M43 to env
  Adding (root Chain).M43B to env
  Adding (root Chain).{M44__}44 to env
  Adding (root Chain).M44 to env
  Adding (root Chain).M44B to env
  Adding (root Chain).{M45__}45 to env
  Adding (root Chain).M45 to env
  Adding (root Chain).M45B to env
  Adding (root Chain).{M46__}46 to env
  Adding (root Chain).M46 to env
  Adding (root Chain).M46B to env
  Adding (root Chain).{M47__}47 to env
  Adding (root Chain).M47 to env
  Adding (root Chain).M47B to env
  Adding (root Chain).{M48__}48 to env
  Adding (root Chain).M48 to env
  Adding (root Chain).M48B to env
  Adding (root Chain).{M49__}49 to env
  Adding (root Chain).M49 to env
  Adding (root Chain).M49B to env
  Adding (root Chain).{M50__}50 to env
  Adding (root Chain).M50 to env
  Adding (root Chain).M50B to env
  Adding (root Chain).{M51__}51 to env
  Adding (root Chain).M51 to env
  Adding (root Chain).M51B to env
  Adding (root Chain).{M52__}52 to env
  Adding (root Chain).M52 to env
  Adding (root Chain).M52B to env
  Adding (root Chain).{M53__}53 to env
  Adding (root Chain).M53 to env
  Adding (root Chain).M53B to env
  Adding (root Chain).{M54__}54 to env
  Adding (root Chain).M54 to env
  Adding (root Chain).M54B to env
  Adding (root Chain).{M55__}55 to env
  Adding (root Chain).M55 to env
  Adding (root Chain).M55B to env
  Adding (root Chain).{M56__}56 to env
  Adding (root Chain).M56 to env
  Adding (root Chain).M56B to env
  Adding (root Chain).{M57__}57 to env
  Adding (root Chain).M57 to env
  Adding (root Chain).M57B to env
  Adding (root Chain).{M58__}58 to env
  Adding (root Chain).M58 to env
  Adding (root Chain).M58B to env
  Adding (root Chain).{M59__}59 to env
  Adding (root Chain).M59 to env
  Adding (root Chain).M59B to env
  Adding (root Chain).{M60__}60 to env
  Adding (root Chain).M60 to env
  Adding (root Chain).M60B to env
  Adding (root Chain).{M61__}61 to env
  Adding (root Chain).M61 to env
  Adding (root Chain).M61B to env
  Adding (root Chain).{M62__}62 to env
  Adding (root Chain).M62 to env
  Adding (root Chain).M62B to env
  Adding (root Chain).{M63__}63 to env
  Adding (root Chain).M63 to env
  Adding (root Chain).M63B to env
  Adding (root Chain).{M64__}64 to env
  Adding (root Chain).M64 to env
  Adding (root Chain).M64B to env
  Adding (root Chain).{M65__}65 to env
  Adding (root Chain).M65 to env
  Adding (root Chain).M65B to env
  Adding (root Chain).{M66__}66 to env
  Adding (root Chain).M66 to env
  Adding (root Chain).M66B to env
  Adding (root Chain).{M67__}67 to env
  Adding (root Chain).M67 to env
  Adding (root Chain).M67B to env
  Adding (root Chain).{M68__}68 to env
  Adding (root Chain).M68 to env
  Adding (root Chain).M68B to env
  Adding (root Chain).{M69__}69 to env
  Adding (root Chain).M69 to env
  Adding (root Chain).M69B to env
  Adding (root Chain).{M70__}70 to env
  Adding (root Chain).M70 to env
  Adding (root Chain).M70B to env
  Adding (root Chain).{M71__}71 to env
  Adding (root Chain).M71 to env
  Adding (root Chain).M71B to env
  Adding (root Chain).{M72__}72 to env
  Adding (root Chain).M72 to env
  Adding (root Chain).M72B to env
  Adding (root Chain).{M73__}73 to env
  Adding (root Chain).M73 to env
  Adding (root Chain).M73B to env
  Adding (root Chain).{M74__}74 to env
  Adding (root Chain).M74 to env
  Adding (root Chain).M74B to env
  Adding (root Chain).{M75__}75 to env
  Adding (root Chain).M75 to env
  Adding (root Chain).M75B to env
  Adding (root Chain).{M76__}76 to env
  Adding (root Chain).M76 to env
  Adding (root Chain).M76B to env
  Adding (root Chain).{M77__}77 to env
  Adding (root Chain).M77 to env
  Adding (root Chain).M77B to env
  Adding (root Chain).{M78__}78 to env
  Adding (root Chain).M78 to env
  Adding (root Chain).M78B to env
  Adding (root Chain).{M79__}79 to env
  Adding (root Chain).M79 to env
  Adding (root Chain).M79B to env
  Adding (root Chain).{M80__}80 to env
  Adding (root Chain).M80 to env
  Adding (root Chain).M80B to env
  Adding (root Chain).{M81__}81 to env
  Adding (root Chain).M81 to env
  Adding (root Chain).M81B to env
  Adding (root Chain).{M82__}82 to env
  Adding (root Chain).M82 to env
  Adding (root Chain).M82B to env
  Adding (root Chain).{M83__}83 to env
  Adding (root Chain).M83 to env
  Adding (root Chain).M83B to env
  Adding (root Chain).{M84__}84 to env
  Adding (root Chain).M84 to env
  Adding (root Chain).M84B to env
  Adding (root Chain).{M85__}85 to env
  Adding (root Chain).M85 to env
  Adding (root Chain).M85B to env
  Adding (root Chain).{M86__}86 to env
  Adding (root Chain).M86 to env
  Adding (root Chain).M86B to env
  Adding (root Chain).{M87__}87 to env
  Adding (root Chain).M87 to env
  Adding (root Chain).M87B to env
  Adding (root Chain).{M88__}88 to env
  Adding (root Chain).M88 to env
  Adding (root Chain).M88B to env
  Adding (root Chain).{M89__}89 to env
  Adding (root Chain).M89 to env
  Adding (root Chain).M89B to env
  Adding (root Chain).{M90__}90 to env
  Adding (root Chain).M90 to env
  Adding (root Chain).M90B to env
  Adding (root Chain).{M91__}91 to env
  Adding (root Chain).M91 to env
  Adding (root Chain).M91B to env
  Adding (root Chain).{M92__}92 to env
  Adding (root Chain).M92 to env
  Adding (root Chain).M92B to env
  Adding (root Chain).{M93__}93 to env
  Adding (root Chain).M93 to env
  Adding (root Chain).M93B to env
  Adding (root Chain).{M94__}94 to env
  Adding (root Chain).M94 to env
  Adding (root Chain).M94B to env
  Adding (root Chain).{M95__}95 to env
  Adding (root Chain).M95 to env
  Adding (root Chain).M95B to env
  Adding (root Chain).{M96__}96 to env
  Adding (root Chain).M96 to env
  Adding (root Chain).M96B to env
  Adding (root Chain).{M97__}97 to env
  Adding (root Chain).M97 to env
  Adding (root Chain).M97B to env
  Adding (root Chain).{M98__}98 to env
  Adding (root Chain).M98 to env
  Adding (root Chain).M98B to env
  Adding (root Chain).{M99__}99 to env
  Adding (root Chain).M99 to env
  Adding (root Chain).M99B to env
  Adding (root Chain).{M100__}100 to env
  Adding (root Chain).M100 to env
  Adding (root Chain).M100B to env
  Adding (root Chain).A.B to env
  Adding (root Chain).A.B.t to env
  Adding (root Chain).M1.B to env
  Adding (root Chain).M2.B to env
  Adding (root Chain).M3.B to env
  Adding (root Chain).M4.B to env
  Adding (root Chain).M5.B to env
  Adding (root Chain).M6.B to env
  Adding (root Chain).M7.B to env
  Adding (root Chain).M8.B to env
  Adding (root Chain).M9.B to env
  Adding (root Chain).M10.B to env
  Adding (root Chain).M11.B to env
  Adding (root Chain).M12.B to env
  Adding (root Chain).M13.B to env
  Adding (root Chain).M14.B to env
  Adding (root Chain).M15.B to env
  Adding (root Chain).M16.B to env
  Adding (root Chain).M17.B to env
  Adding (root Chain).M18.B to env
  Adding (root Chain).M19.B to env
  Adding (root Chain).M20.B to env
  Adding (root Chain).M21.B to env
  Adding (root Chain).M22.B to env
  Adding (root Chain).M23.B to env
  Adding (root Chain).M24.B to env
  Adding (root Chain).M25.B to env
  Adding (root Chain).M26.B to env
  Adding (root Chain).M27.B to env
  Adding (root Chain).M28.B to env
  Adding (root Chain).M29.B to env
  Adding (root Chain).M30.B to env
  Adding (root Chain).M31.B to env
  Adding (root Chain).M32.B to env
  Adding (root Chain).M33.B to env
  Adding (root Chain).M34.B to env
  Adding (root Chain).M35.B to env
  Adding (root Chain).M36.B to env
  Adding (root Chain).M37.B to env
  Adding (root Chain).M38.B to env
  Adding (root Chain).M39.B to env
  Adding (root Chain).M40.B to env
  Adding (root Chain).M41.B to env
  Adding (root Chain).M42.B to env
  Adding (root Chain).M43.B to env
  Adding (root Chain).M44.B to env
  Adding (root Chain).M45.B to env
  Adding (root Chain).M46.B to env
  Adding (root Chain).M47.B to env
  Adding (root Chain).M48.B to env
  Adding (root Chain).M49.B to env
  Adding (root Chain).M50.B to env
  Adding (root Chain).M51.B to env
  Adding (root Chain).M52.B to env
  Adding (root Chain).M53.B to env
  Adding (root Chain).M54.B to env
  Adding (root Chain).M55.B to env
  Adding (root Chain).M56.B to env
  Adding (root Chain).M57.B to env
  Adding (root Chain).M58.B to env
  Adding (root Chain).M59.B to env
  Adding (root Chain).M60.B to env
  Adding (root Chain).M61.B to env
  Adding (root Chain).M62.B to env
  Adding (root Chain).M63.B to env
  Adding (root Chain).M64.B to env
  Adding (root Chain).M65.B to env
  Adding (root Chain).M66.B to env
  Adding (root Chain).M67.B to env
  Adding (root Chain).M68.B to env
  Adding (root Chain).M69.B to env
  Adding (root Chain).M70.B to env
  Adding (root Chain).M71.B to env
  Adding (root Chain).M72.B to env
  Adding (root Chain).M73.B to env
  Adding (root Chain).M74.B to env
  Adding (root Chain).M75.B to env
  Adding (root Chain).M76.B to env
  Adding (root Chain).M77.B to env
  Adding (root Chain).M78.B to env
  Adding (root Chain).M79.B to env
  Adding (root Chain).M80.B to env
  Adding (root Chain).M81.B to env
  Adding (root Chain).M82.B to env
  Adding (root Chain).M83.B to env
  Adding (root Chain).M84.B to env
  Adding (root Chain).M85.B to env
  Adding (root Chain).M86.B to env
  Adding (root Chain).M87.B to env
  Adding (root Chain).M88.B to env
  Adding (root Chain).M89.B to env
  Adding (root Chain).M90.B to env
  Adding (root Chain).M91.B to env
  Adding (root Chain).M92.B to env
  Adding (root Chain).M93.B to env
  Adding (root Chain).M94.B to env
  Adding (root Chain).M95.B to env
  Adding (root Chain).M96.B to env
  Adding (root Chain).M97.B to env
  Adding (root Chain).M98.B to env
  Adding (root Chain).M99.B to env
  Adding (root Chain).M100.B to env
  $ find . -name chain.odocl -size +100000c 
