A long chain of aliases should produce an odocl file that's a reasonable
size.

  $ ocamlc -c -bin-annot chain.mli
  $ odoc compile chain.cmti
  $ odoc link chain.odoc -I .
  module: (root Chain).A
  module: (root Chain).A.B
  module: (root Chain).{M1__}1
  module: (root Chain).M1
  module: (root Chain).M1.B
  module: (root Chain).M1B
  module: (root Chain).{M2__}2
  module: (root Chain).M2
  module: (root Chain).M2.B
  module: (root Chain).M2B
  module: (root Chain).{M3__}3
  module: (root Chain).M3
  module: (root Chain).M3.B
  module: (root Chain).M3B
  module: (root Chain).{M4__}4
  module: (root Chain).M4
  module: (root Chain).M4.B
  module: (root Chain).M4B
  module: (root Chain).{M5__}5
  module: (root Chain).M5
  module: (root Chain).M5.B
  module: (root Chain).M5B
  module: (root Chain).{M6__}6
  module: (root Chain).M6
  module: (root Chain).M6.B
  module: (root Chain).M6B
  module: (root Chain).{M7__}7
  module: (root Chain).M7
  module: (root Chain).M7.B
  module: (root Chain).M7B
  module: (root Chain).{M8__}8
  module: (root Chain).M8
  module: (root Chain).M8.B
  module: (root Chain).M8B
  module: (root Chain).{M9__}9
  module: (root Chain).M9
  module: (root Chain).M9.B
  module: (root Chain).M9B
  module: (root Chain).{M10__}10
  module: (root Chain).M10
  module: (root Chain).M10.B
  module: (root Chain).M10B
  module: (root Chain).{M11__}11
  module: (root Chain).M11
  module: (root Chain).M11.B
  module: (root Chain).M11B
  module: (root Chain).{M12__}12
  module: (root Chain).M12
  module: (root Chain).M12.B
  module: (root Chain).M12B
  module: (root Chain).{M13__}13
  module: (root Chain).M13
  module: (root Chain).M13.B
  module: (root Chain).M13B
  module: (root Chain).{M14__}14
  module: (root Chain).M14
  module: (root Chain).M14.B
  module: (root Chain).M14B
  module: (root Chain).{M15__}15
  module: (root Chain).M15
  module: (root Chain).M15.B
  module: (root Chain).M15B
  module: (root Chain).{M16__}16
  module: (root Chain).M16
  module: (root Chain).M16.B
  module: (root Chain).M16B
  module: (root Chain).{M17__}17
  module: (root Chain).M17
  module: (root Chain).M17.B
  module: (root Chain).M17B
  module: (root Chain).{M18__}18
  module: (root Chain).M18
  module: (root Chain).M18.B
  module: (root Chain).M18B
  module: (root Chain).{M19__}19
  module: (root Chain).M19
  module: (root Chain).M19.B
  module: (root Chain).M19B
  module: (root Chain).{M20__}20
  module: (root Chain).M20
  module: (root Chain).M20.B
  module: (root Chain).M20B
  module: (root Chain).{M21__}21
  module: (root Chain).M21
  module: (root Chain).M21.B
  module: (root Chain).M21B
  module: (root Chain).{M22__}22
  module: (root Chain).M22
  module: (root Chain).M22.B
  module: (root Chain).M22B
  module: (root Chain).{M23__}23
  module: (root Chain).M23
  module: (root Chain).M23.B
  module: (root Chain).M23B
  module: (root Chain).{M24__}24
  module: (root Chain).M24
  module: (root Chain).M24.B
  module: (root Chain).M24B
  module: (root Chain).{M25__}25
  module: (root Chain).M25
  module: (root Chain).M25.B
  module: (root Chain).M25B
  module: (root Chain).{M26__}26
  module: (root Chain).M26
  module: (root Chain).M26.B
  module: (root Chain).M26B
  module: (root Chain).{M27__}27
  module: (root Chain).M27
  module: (root Chain).M27.B
  module: (root Chain).M27B
  module: (root Chain).{M28__}28
  module: (root Chain).M28
  module: (root Chain).M28.B
  module: (root Chain).M28B
  module: (root Chain).{M29__}29
  module: (root Chain).M29
  module: (root Chain).M29.B
  module: (root Chain).M29B
  module: (root Chain).{M30__}30
  module: (root Chain).M30
  module: (root Chain).M30.B
  module: (root Chain).M30B
  module: (root Chain).{M31__}31
  module: (root Chain).M31
  module: (root Chain).M31.B
  module: (root Chain).M31B
  module: (root Chain).{M32__}32
  module: (root Chain).M32
  module: (root Chain).M32.B
  module: (root Chain).M32B
  module: (root Chain).{M33__}33
  module: (root Chain).M33
  module: (root Chain).M33.B
  module: (root Chain).M33B
  module: (root Chain).{M34__}34
  module: (root Chain).M34
  module: (root Chain).M34.B
  module: (root Chain).M34B
  module: (root Chain).{M35__}35
  module: (root Chain).M35
  module: (root Chain).M35.B
  module: (root Chain).M35B
  module: (root Chain).{M36__}36
  module: (root Chain).M36
  module: (root Chain).M36.B
  module: (root Chain).M36B
  module: (root Chain).{M37__}37
  module: (root Chain).M37
  module: (root Chain).M37.B
  module: (root Chain).M37B
  module: (root Chain).{M38__}38
  module: (root Chain).M38
  module: (root Chain).M38.B
  module: (root Chain).M38B
  module: (root Chain).{M39__}39
  module: (root Chain).M39
  module: (root Chain).M39.B
  module: (root Chain).M39B
  module: (root Chain).{M40__}40
  module: (root Chain).M40
  module: (root Chain).M40.B
  module: (root Chain).M40B
  module: (root Chain).{M41__}41
  module: (root Chain).M41
  module: (root Chain).M41.B
  module: (root Chain).M41B
  module: (root Chain).{M42__}42
  module: (root Chain).M42
  module: (root Chain).M42.B
  module: (root Chain).M42B
  module: (root Chain).{M43__}43
  module: (root Chain).M43
  module: (root Chain).M43.B
  module: (root Chain).M43B
  module: (root Chain).{M44__}44
  module: (root Chain).M44
  module: (root Chain).M44.B
  module: (root Chain).M44B
  module: (root Chain).{M45__}45
  module: (root Chain).M45
  module: (root Chain).M45.B
  module: (root Chain).M45B
  module: (root Chain).{M46__}46
  module: (root Chain).M46
  module: (root Chain).M46.B
  module: (root Chain).M46B
  module: (root Chain).{M47__}47
  module: (root Chain).M47
  module: (root Chain).M47.B
  module: (root Chain).M47B
  module: (root Chain).{M48__}48
  module: (root Chain).M48
  module: (root Chain).M48.B
  module: (root Chain).M48B
  module: (root Chain).{M49__}49
  module: (root Chain).M49
  module: (root Chain).M49.B
  module: (root Chain).M49B
  module: (root Chain).{M50__}50
  module: (root Chain).M50
  module: (root Chain).M50.B
  module: (root Chain).M50B
  module: (root Chain).{M51__}51
  module: (root Chain).M51
  module: (root Chain).M51.B
  module: (root Chain).M51B
  module: (root Chain).{M52__}52
  module: (root Chain).M52
  module: (root Chain).M52.B
  module: (root Chain).M52B
  module: (root Chain).{M53__}53
  module: (root Chain).M53
  module: (root Chain).M53.B
  module: (root Chain).M53B
  module: (root Chain).{M54__}54
  module: (root Chain).M54
  module: (root Chain).M54.B
  module: (root Chain).M54B
  module: (root Chain).{M55__}55
  module: (root Chain).M55
  module: (root Chain).M55.B
  module: (root Chain).M55B
  module: (root Chain).{M56__}56
  module: (root Chain).M56
  module: (root Chain).M56.B
  module: (root Chain).M56B
  module: (root Chain).{M57__}57
  module: (root Chain).M57
  module: (root Chain).M57.B
  module: (root Chain).M57B
  module: (root Chain).{M58__}58
  module: (root Chain).M58
  module: (root Chain).M58.B
  module: (root Chain).M58B
  module: (root Chain).{M59__}59
  module: (root Chain).M59
  module: (root Chain).M59.B
  module: (root Chain).M59B
  module: (root Chain).{M60__}60
  module: (root Chain).M60
  module: (root Chain).M60.B
  module: (root Chain).M60B
  module: (root Chain).{M61__}61
  module: (root Chain).M61
  module: (root Chain).M61.B
  module: (root Chain).M61B
  module: (root Chain).{M62__}62
  module: (root Chain).M62
  module: (root Chain).M62.B
  module: (root Chain).M62B
  module: (root Chain).{M63__}63
  module: (root Chain).M63
  module: (root Chain).M63.B
  module: (root Chain).M63B
  module: (root Chain).{M64__}64
  module: (root Chain).M64
  module: (root Chain).M64.B
  module: (root Chain).M64B
  module: (root Chain).{M65__}65
  module: (root Chain).M65
  module: (root Chain).M65.B
  module: (root Chain).M65B
  module: (root Chain).{M66__}66
  module: (root Chain).M66
  module: (root Chain).M66.B
  module: (root Chain).M66B
  module: (root Chain).{M67__}67
  module: (root Chain).M67
  module: (root Chain).M67.B
  module: (root Chain).M67B
  module: (root Chain).{M68__}68
  module: (root Chain).M68
  module: (root Chain).M68.B
  module: (root Chain).M68B
  module: (root Chain).{M69__}69
  module: (root Chain).M69
  module: (root Chain).M69.B
  module: (root Chain).M69B
  module: (root Chain).{M70__}70
  module: (root Chain).M70
  module: (root Chain).M70.B
  module: (root Chain).M70B
  module: (root Chain).{M71__}71
  module: (root Chain).M71
  module: (root Chain).M71.B
  module: (root Chain).M71B
  module: (root Chain).{M72__}72
  module: (root Chain).M72
  module: (root Chain).M72.B
  module: (root Chain).M72B
  module: (root Chain).{M73__}73
  module: (root Chain).M73
  module: (root Chain).M73.B
  module: (root Chain).M73B
  module: (root Chain).{M74__}74
  module: (root Chain).M74
  module: (root Chain).M74.B
  module: (root Chain).M74B
  module: (root Chain).{M75__}75
  module: (root Chain).M75
  module: (root Chain).M75.B
  module: (root Chain).M75B
  module: (root Chain).{M76__}76
  module: (root Chain).M76
  module: (root Chain).M76.B
  module: (root Chain).M76B
  module: (root Chain).{M77__}77
  module: (root Chain).M77
  module: (root Chain).M77.B
  module: (root Chain).M77B
  module: (root Chain).{M78__}78
  module: (root Chain).M78
  module: (root Chain).M78.B
  module: (root Chain).M78B
  module: (root Chain).{M79__}79
  module: (root Chain).M79
  module: (root Chain).M79.B
  module: (root Chain).M79B
  module: (root Chain).{M80__}80
  module: (root Chain).M80
  module: (root Chain).M80.B
  module: (root Chain).M80B
  module: (root Chain).{M81__}81
  module: (root Chain).M81
  module: (root Chain).M81.B
  module: (root Chain).M81B
  module: (root Chain).{M82__}82
  module: (root Chain).M82
  module: (root Chain).M82.B
  module: (root Chain).M82B
  module: (root Chain).{M83__}83
  module: (root Chain).M83
  module: (root Chain).M83.B
  module: (root Chain).M83B
  module: (root Chain).{M84__}84
  module: (root Chain).M84
  module: (root Chain).M84.B
  module: (root Chain).M84B
  module: (root Chain).{M85__}85
  module: (root Chain).M85
  module: (root Chain).M85.B
  module: (root Chain).M85B
  module: (root Chain).{M86__}86
  module: (root Chain).M86
  module: (root Chain).M86.B
  module: (root Chain).M86B
  module: (root Chain).{M87__}87
  module: (root Chain).M87
  module: (root Chain).M87.B
  module: (root Chain).M87B
  module: (root Chain).{M88__}88
  module: (root Chain).M88
  module: (root Chain).M88.B
  module: (root Chain).M88B
  module: (root Chain).{M89__}89
  module: (root Chain).M89
  module: (root Chain).M89.B
  module: (root Chain).M89B
  module: (root Chain).{M90__}90
  module: (root Chain).M90
  module: (root Chain).M90.B
  module: (root Chain).M90B
  module: (root Chain).{M91__}91
  module: (root Chain).M91
  module: (root Chain).M91.B
  module: (root Chain).M91B
  module: (root Chain).{M92__}92
  module: (root Chain).M92
  module: (root Chain).M92.B
  module: (root Chain).M92B
  module: (root Chain).{M93__}93
  module: (root Chain).M93
  module: (root Chain).M93.B
  module: (root Chain).M93B
  module: (root Chain).{M94__}94
  module: (root Chain).M94
  module: (root Chain).M94.B
  module: (root Chain).M94B
  module: (root Chain).{M95__}95
  module: (root Chain).M95
  module: (root Chain).M95.B
  module: (root Chain).M95B
  module: (root Chain).{M96__}96
  module: (root Chain).M96
  module: (root Chain).M96.B
  module: (root Chain).M96B
  module: (root Chain).{M97__}97
  module: (root Chain).M97
  module: (root Chain).M97.B
  module: (root Chain).M97B
  module: (root Chain).{M98__}98
  module: (root Chain).M98
  module: (root Chain).M98.B
  module: (root Chain).M98B
  module: (root Chain).{M99__}99
  module: (root Chain).M99
  module: (root Chain).M99.B
  module: (root Chain).M99B
  module: (root Chain).{M100__}100
  module: (root Chain).M100
  module: (root Chain).M100.B
  module: (root Chain).M100B
  $ find . -name chain.odocl -size +100000c 
